/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/privateRoute'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PrivateRouteRoute = PrivateRouteImport.update({
  path: '/privateRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/privateRoute': {
      id: '/privateRoute'
      path: '/privateRoute'
      fullPath: '/privateRoute'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privateRoute': typeof PrivateRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privateRoute': typeof PrivateRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/privateRoute': typeof PrivateRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privateRoute'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privateRoute'
  id: '__root__' | '/' | '/privateRoute'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/privateRoute"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/privateRoute": {
      "filePath": "privateRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
